CFLAGS=-Wall -Wextra -std=c11 -g

all:
	make ex01
	make ex03
	make ex04
	make ex05
	make ex06
	make ex07
	make ex08
	make ex09
	make ex10
	make ex11
	make ex12
	make ex13
	make ex14
	make ex15
	make ex16
	make ex17
	make ex18
	make ex19
	make ex20

clean:
	rm -f ex01
	rm -f ex03
	rm -f ex04
	rm -f ex05
	rm -f ex06
	rm -f ex07
	rm -f ex08
	rm -f ex09
	rm -f ex10
	rm -f ex11
	rm -f ex12
	rm -f ex13
	rm -f ex14
	rm -f ex15
	rm -f ex16
	rm -f ex17
	rm -f ex18
	rm -f ex19
	rm -f ex20
