CFLAGS=-Wall -Wextra -g

all:
	make ex01
	make ex03
	make ex04
	make ex05
	make ex06
	make ex07
	make ex08
	make ex09
	make ex10

clean:
	rm -f ex01
	rm -f ex03
	rm -f ex04
	rm -f ex05
	rm -f ex06
	rm -f ex07
	rm -f ex08
	rm -f ex09
	rm -f ex10
